export const jobs = [
  {
    id: 'job-1',
    title: 'Housekeeper / Maid',
    title_hi: 'मेड/हाउसकीपर',
    category: 'Household',
    salary: '₹8,000 / week',
    distance: '1.2 km',
    employerName: 'Sharma Family',
    verified: true,
    rating: 4.8,
    description: 'Light housekeeping, cleaning, basic cooking. Morning shift. Immediate join.',
    description_hi: 'हाउसकीपिंग, सफाई, आसान खाना बनाना। सुबह की शिफ्ट। तुरंत शामिल।',
    location: 'Sector 5, Gurgaon',
    shift: 'Morning',
    contact: ''
  },
  {
    id: 'job-2',
    title: 'Delivery Partner (Bike)',
    title_hi: 'डिलीवरी पार्टनर (बाइक)',
    category: 'Delivery',
    salary: '₹18,000 / month',
    distance: '3.4 km',
    employerName: 'QuickShip',
    verified: false,
    rating: 4.2,
    description: 'Deliver packages across nearby zones. Bike required. Flexible timings.',
    description_hi: 'नज़दीकी एरिया में पैकेज डिलीवरी। बाइक जरूरी। लचीले समय।',
    location: 'Saket, Delhi',
    shift: 'Flexible',
    contact: ''
  },
  {
    id: 'job-3',
    title: 'Security Guard (Night)',
    title_hi: 'सिक्योरिटी गार्ड (नाइट)',
    category: 'Security',
    salary: '₹12,000 / month',
    distance: '0.9 km',
    employerName: 'Galaxy Apartments',
    verified: true,
    rating: 4.6,
    description: 'Night shift security for apartment complex. Prior experience preferred.',
    description_hi: 'अपार्टमेंट परिसर के लिए नाइट शिफ्ट सुरक्षा। अनुभव वांछित।',
    location: 'Andheri East, Mumbai',
    shift: 'Night',
    contact: ''
  },
  {
    id: 'job-4',
    title: 'Plumber (Part-time)',
    title_hi: 'प्लंबर (पार्ट-टाइम)',
    category: 'Maintenance',
    salary: '₹500 / visit',
    distance: '2.7 km',
    employerName: 'Local Contractor',
    verified: false,
    rating: 4.4,
    description: 'Fix basic plumbing issues and leaks. Tools preferred but not required.',
    description_hi: 'प्लंबिंग मुद्दे और लीक ठीक करें। उपकरण हो तो बेहतर।',
    location: 'Koramangala, Bangalore',
    shift: 'On-call',
    contact: ''
  },
  {
    id: 'job-5',
    title: 'Electrician (Home)',
    title_hi: 'इलेक्ट्रीशियन',
    category: 'Maintenance',
    salary: '₹600 / visit',
    distance: '1.8 km',
    employerName: 'PowerFix',
    verified: true,
    rating: 4.5,
    description: 'Small home electrical repairs, wiring, fan and light fixes.',
    description_hi: 'छोटे घरेलू विद्युत मरम्मत, वायरिंग, पंखा और लाइट फिक्स।',
    location: 'Kohima, Nagaland',
    shift: 'On-call',
    contact: ''
  },
  {
    id: 'job-6',
    title: 'Cook (Home)',
    title_hi: 'घरेलू रसोइया',
    category: 'Household',
    salary: '₹10,000 / month',
    distance: '4.0 km',
    employerName: 'Mehra Family',
    verified: false,
    rating: 4.1,
    description: 'Prepare daily meals for a family of 4. Clean kitchen after cooking.',
    description_hi: '4 व्यक्तियों के लिए दैनिक भोजन तैयार करें। खाना पकाने के बाद रसोई साफ करें।',
    location: 'Noida, UP',
    shift: 'Morning/Evening',
    contact: ''
  },
  {
    id: 'job-7',
    title: 'Gardener',
    title_hi: 'माली',
    category: 'Outdoor',
    salary: '₹7,000 / month',
    distance: '2.2 km',
    employerName: 'GreenHomes',
    verified: true,
    rating: 4.7,
    description: 'Maintain plants, water garden, basic landscaping tasks.',
    description_hi: 'पौधों की देखभाल, बगीचे को पानी देना, बुनियादी लैंडस्केपिंग कार्य।',
    location: 'Pune, Maharashtra',
    shift: 'Morning',
    contact: ''
  },
  {
    id: 'job-8',
    title: 'Painter (House)',
    title_hi: 'पेंटर',
    category: 'Maintenance',
    salary: '₹1,500 / day',
    distance: '6.0 km',
    employerName: 'ColorCraft',
    verified: false,
    rating: 4.0,
    description: 'Interior and exterior painting jobs. Materials provided sometimes.',
    description_hi: 'इंटीरियर और एक्सटीरियर पेंटिंग। सामग्री कभी-कभी प्रदान की जाती है।',
    location: 'Jayanagar, Bangalore',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-9',
    title: 'Carpenter',
    title_hi: 'कारपेंटर',
    category: 'Maintenance',
    salary: '₹350 / visit',
    distance: '3.1 km',
    employerName: 'WoodWorks',
    verified: true,
    rating: 4.3,
    description: 'Basic carpentry work: furniture repair and small installations.',
    description_hi: 'बुनियादी बढ़ईगीरी: फर्नीचर मरम्मत और छोटे इंस्टालेशन।',
    location: 'Salt Lake, Kolkata',
    shift: 'On-call',
    contact: ''
  },
  {
    id: 'job-10',
    title: 'Tailor / Stitcher',
    title_hi: ' दर्ज़ी',
    category: 'Craft',
    salary: '₹12,000 / month',
    distance: '0.7 km',
    employerName: 'Sona Tailors',
    verified: false,
    rating: 4.0,
    description: 'Stitching, alterations and minor tailoring tasks.',
    description_hi: 'सिलाई, अल्ट्रेशन और छोटे दर्ज़ी कार्य।',
    location: 'Vishakhapatnam, AP',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-11',
    title: 'Construction Labourer',
    title_hi: 'निर्माण मजदूर',
    category: 'Construction',
    salary: '₹500 / day',
    distance: '5.0 km',
    employerName: 'BuildRight',
    verified: true,
    rating: 4.4,
    description: 'Assist in basic construction work, carrying materials and site cleaning.',
    description_hi: 'बुनियादी निर्माण कार्य में सहायता, सामग्री ले जाना और साइट की सफाई।',
    location: 'Gurgaon, Haryana',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-12',
    title: 'Shop Assistant (Grocery)',
    title_hi: 'दुकानदार सहायक',
    category: 'Retail',
    salary: '₹11,000 / month',
    distance: '0.5 km',
    employerName: 'DailyMart',
    verified: false,
    rating: 3.9,
    description: 'Stocking shelves, billing assistance, customer help.',
    description_hi: 'शेल्फ भरना, बिलिंग में सहायता, ग्राहक सहायता।',
    location: 'Ajmer, Rajasthan',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-13',
    title: 'Washer / Laundry',
    title_hi: 'लॉन्ड्री वॉशर',
    category: 'Household',
    salary: '₹300 / day',
    distance: '3.3 km',
    employerName: 'CleanWave',
    verified: true,
    rating: 4.2,
    description: 'Clothes washing and basic ironing tasks.',
    description_hi: 'कपड़े धुलाई और बुनियादी इस्त्री कार्य।',
    location: 'Kochi, Kerala',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-14',
    title: 'Babysitter / Nanny',
    title_hi: 'बेबीसिटर / नैनी',
    category: 'Care',
    salary: '₹9,000 / month',
    distance: '2.0 km',
    employerName: 'Kapur Family',
    verified: false,
    rating: 4.1,
    description: 'Childcare for toddlers, feeding, basic play and safety.',
    description_hi: 'शिशु की देखभाल, खाना खिलाना, खेल और सुरक्षा।',
    location: 'Thane, Maharashtra',
    shift: 'Morning/Afternoon',
    contact: ''
  },
  {
    id: 'job-15',
    title: 'Caregiver (Elderly)',
    title_hi: 'देखभालकर्ता (बुज़ुर्ग)',
    category: 'Care',
    salary: '₹10,500 / month',
    distance: '1.1 km',
    employerName: 'SeniorCare',
    verified: true,
    rating: 4.7,
    description: 'Assist elderly with daily activities, medication reminders.',
    description_hi: 'दैनिक गतिविधियों में बुज़ुर्गों की मदद, दवा की याद दिलाना।',
    location: 'Patna, Bihar',
    shift: 'Day/Night',
    contact: ''
  },
  {
    id: 'job-16',
    title: 'Retail Cashier',
    title_hi: 'किराने काउंटर',
    category: 'Retail',
    salary: '₹11,500 / month',
    distance: '0.8 km',
    employerName: 'SmartStore',
    verified: false,
    rating: 4.0,
    description: 'Operate billing, handle cash and simple customer queries.',
    description_hi: 'बिलिंग करना, नकदी संभालना और सरल ग्राहक प्रश्न।',
    location: 'Cuttack, Odisha',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-17',
    title: 'Tea Stall Attendant',
    title_hi: 'चाय स्टॉल सहायक',
    category: 'Food',
    salary: '₹300 / day',
    distance: '0.3 km',
    employerName: 'Ram Tea',
    verified: false,
    rating: 4.1,
    description: 'Prepare and serve tea, keep stall clean and tidy.',
    description_hi: 'चाय बनाना और परोसना, स्टॉल साफ रखना।',
    location: 'Varanasi, UP',
    shift: 'Morning',
    contact: ''
  },
  {
    id: 'job-18',
    title: 'Roadside Vendor Helper',
    title_hi: 'सड़क किनारे विक्रेता सहायक',
    category: 'Retail',
    salary: '₹9,000 / month',
    distance: '1.4 km',
    employerName: 'StreetBites',
    verified: false,
    rating: 3.8,
    description: 'Assist in food prep, serving, and cash collection.',
    description_hi: 'खाना तैयार करने, परोसने और नकदी संग्रह में मदद।',
    location: 'Lucknow, UP',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-19',
    title: 'Auto Driver (Local)',
    title_hi: 'ऑटो ड्राइवर',
    category: 'Transport',
    salary: '₹18,000 / month',
    distance: '2.9 km',
    employerName: 'CityRides',
    verified: true,
    rating: 4.3,
    description: 'Local passenger transport, good city knowledge required.',
    description_hi: 'स्थानीय यात्री परिवहन, अच्छा शहर ज्ञान आवश्यक।',
    location: 'Ahmedabad, Gujarat',
    shift: 'Flexible',
    contact: ''
  },
  {
    id: 'job-20',
    title: 'Truck Driver',
    title_hi: 'ट्रक ड्राइवर',
    category: 'Transport',
    salary: '₹25,000 / month',
    distance: '12.0 km',
    employerName: 'HaulCo',
    verified: true,
    rating: 4.6,
    description: 'Intercity goods transport. Valid license required.',
    description_hi: 'इंटरसिटी माल परिवहन। वैध लाइसेंस आवश्यक।',
    location: 'Jalandhar, Punjab',
    shift: 'Day/Night',
    contact: ''
  },
  {
    id: 'job-21',
    title: 'Mechanic (Two-wheeler)',
    title_hi: 'दो-पहिया मैकेनिक',
    category: 'Automotive',
    salary: '₹15,000 / month',
    distance: '4.4 km',
    employerName: 'MotoCare',
    verified: false,
    rating: 4.2,
    description: 'Repair and servicing of two-wheelers.',
    description_hi: 'दो-पहिया वाहनों की मरम्मत और सर्विसिंग।',
    location: 'Bhubaneswar, Odisha',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-22',
    title: 'AC Technician',
    title_hi: 'एसी टेक्नीशियन',
    category: 'Maintenance',
    salary: '₹800 / visit',
    distance: '6.2 km',
    employerName: 'CoolFix',
    verified: true,
    rating: 4.5,
    description: 'AC servicing, gas top-up, and minor repairs.',
    description_hi: 'एसी सर्विसिंग, गैस टॉप-अप और छोटे मरम्मत।',
    location: 'Nagpur, Maharashtra',
    shift: 'On-call',
    contact: ''
  },
  {
    id: 'job-23',
    title: 'CCTV Installer',
    title_hi: 'सीसीटीवी इंस्टॉलर',
    category: 'Security',
    salary: '₹900 / visit',
    distance: '7.8 km',
    employerName: 'SecureHome',
    verified: false,
    rating: 4.1,
    description: 'Install and configure CCTV cameras for homes and shops.',
    description_hi: 'घरों और दुकानों के लिए सीसीटीवी कैमरे इंस्टॉल और कॉन्फ़िगर करें।',
    location: 'Indore, MP',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-24',
    title: 'Beautician (Home Service)',
    title_hi: 'ब्यूटीशियन',
    category: 'Personal Care',
    salary: '₹600 / service',
    distance: '3.0 km',
    employerName: 'GlowCare',
    verified: false,
    rating: 4.0,
    description: 'Basic beauty services at home: threading, manicure.',
    description_hi: 'घरेलू सेवा पर बुनियादी ब्यूटी सेवाएं: थ्रेडिंग, मैनीक्योर।',
    location: 'Thiruvananthapuram, Kerala',
    shift: 'Flexible',
    contact: ''
  },
  {
    id: 'job-25',
    title: 'Barber',
    title_hi: 'नाई',
    category: 'Personal Care',
    salary: '₹350 / day',
    distance: '0.6 km',
    employerName: 'CutNStyle',
    verified: true,
    rating: 4.3,
    description: 'Haircuts and basic grooming services.',
    description_hi: 'हेयरकट और बुनियादी ग्रूमिंग सेवाएं।',
    location: 'Ranchi, Jharkhand',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-26',
    title: 'Baker (Small Shop)',
    title_hi: 'बेकरी कर्मचारी',
    category: 'Food',
    salary: '₹10,000 / month',
    distance: '2.5 km',
    employerName: 'BakeHouse',
    verified: false,
    rating: 4.0,
    description: 'Prepare bread, cakes and assist with bakery operations.',
    description_hi: 'ब्रेड, केक बनाना और बेकरी संचालन में सहायता।',
    location: 'Dehradun, Uttarakhand',
    shift: 'Morning',
    contact: ''
  },
  {
    id: 'job-27',
    title: 'Florist Assistant',
    title_hi: 'फ्लोरिस्ट सहायक',
    category: 'Retail',
    salary: '₹9,500 / month',
    distance: '1.9 km',
    employerName: 'BloomBox',
    verified: false,
    rating: 4.2,
    description: 'Arrange flowers, make bouquets and assist customers.',
    description_hi: 'फूल सजाना, गुलदस्ते बनाना और ग्राहकों की सहायता।',
    location: 'Mysore, Karnataka',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-28',
    title: 'Hotel Room Attendant',
    title_hi: 'होटल रूम अटेंडेंट',
    category: 'Hospitality',
    salary: '₹12,000 / month',
    distance: '6.5 km',
    employerName: 'Sunrise Hotel',
    verified: true,
    rating: 4.4,
    description: 'Clean rooms, change linens, basic guest service.',
    description_hi: 'कमरे साफ करें, लिनन बदलें, बुनियादी अतिथि सेवा।',
    location: 'Shimla, Himachal Pradesh',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-29',
    title: 'Parcel Sorter (Warehouse)',
    title_hi: 'पार्सल सॉर्टर',
    category: 'Warehouse',
    salary: '₹10,500 / month',
    distance: '8.0 km',
    employerName: 'FastFulfill',
    verified: true,
    rating: 4.2,
    description: 'Sort parcels by zone and prepare shipments.',
    description_hi: 'क्षेत्र के अनुसार पार्सल छांटना और शिपमेंट तैयार करना।',
    location: 'Faridabad, Haryana',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-30',
    title: 'Warehouse Picker',
    title_hi: 'वेयरहाउस पिकर',
    category: 'Warehouse',
    salary: '₹10,000 / month',
    distance: '7.2 km',
    employerName: 'StoreLink',
    verified: false,
    rating: 4.0,
    description: 'Pick items for orders and pack them.',
    description_hi: 'ऑर्डर के लिए आइटम उठाना और पैक करना।',
    location: 'Guwahati, Assam',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-31',
    title: 'Factory Helper',
    title_hi: 'कारखाना सहायक',
    category: 'Manufacturing',
    salary: '₹9,000 / month',
    distance: '10.0 km',
    employerName: 'MetalWorks',
    verified: false,
    rating: 3.9,
    description: 'Assist in assembly line and basic machine tasks.',
    description_hi: 'असेंबली लाइन में सहायता और बुनियादी मशीन कार्य।',
    location: 'Dhanbad, Jharkhand',
    shift: 'Day/Night',
    contact: ''
  },
  {
    id: 'job-32',
    title: 'Forklift Operator',
    title_hi: 'फोर्कलिफ्ट ऑपरेटर',
    category: 'Warehouse',
    salary: '₹16,000 / month',
    distance: '9.5 km',
    employerName: 'LiftMove',
    verified: true,
    rating: 4.5,
    description: 'Operate forklift for loading and unloading pallets.',
    description_hi: 'पैलेट लोडिंग और अनलोडिंग के लिए फोर्कलिफ्ट चलाना।',
    location: 'Surat, Gujarat',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-33',
    title: 'Machine Operator',
    title_hi: 'मशीन ऑपरेटर',
    category: 'Manufacturing',
    salary: '₹14,000 / month',
    distance: '11.2 km',
    employerName: 'SpinTech',
    verified: false,
    rating: 4.1,
    description: 'Operate and monitor production machines.',
    description_hi: 'उत्पादन मशीनों का संचालन और निगरानी।',
    location: 'Jamshedpur, Jharkhand',
    shift: 'Day/Night',
    contact: ''
  },
  {
    id: 'job-34',
    title: 'Pest Control Technician',
    title_hi: 'पेस्ट कंट्रोल टेक्नीशियन',
    category: 'Maintenance',
    salary: '₹700 / visit',
    distance: '4.6 km',
    employerName: 'SafeHome',
    verified: true,
    rating: 4.4,
    description: 'Home pest control services, safe chemicals used.',
    description_hi: 'घरेलू कीट नियंत्रण सेवाएं, सुरक्षित रसायन उपयोग।',
    location: 'Agra, UP',
    shift: 'On-call',
    contact: ''
  },
  {
    id: 'job-35',
    title: 'Security Supervisor',
    title_hi: 'सिक्योरिटी सुपरवाइज़र',
    category: 'Security',
    salary: '₹18,000 / month',
    distance: '3.0 km',
    employerName: 'SecureCorp',
    verified: true,
    rating: 4.6,
    description: 'Manage a small team of security guards, oversee shifts.',
    description_hi: 'सिक्योरिटी गार्डों की छोटी टीम का प्रबंधन, शिफ्ट की निगरानी।',
    location: 'Chandigarh',
    shift: 'Day/Night',
    contact: ''
  },
  {
    id: 'job-36',
    title: 'Roofer / Tiler',
    title_hi: 'छत/टाइल लगने वाला',
    category: 'Construction',
    salary: '₹600 / day',
    distance: '15.0 km',
    employerName: 'TopBuild',
    verified: false,
    rating: 4.0,
    description: 'Roof repairs and tile installation work.',
    description_hi: 'छत की मरम्मत और टाइल स्थापना कार्य।',
    location: 'Alleppey, Kerala',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-37',
    title: 'Cleaner (Office)',
    title_hi: 'क्लीनर (ऑफिस)',
    category: 'Household',
    salary: '₹9,500 / month',
    distance: '0.9 km',
    employerName: 'OfficeCare',
    verified: false,
    rating: 4.0,
    description: 'Daily office cleaning and basic maintenance.',
    description_hi: 'दैनिक कार्यालय की सफाई और बुनियादी रखरखाव।',
    location: 'Bikaner, Rajasthan',
    shift: 'Morning',
    contact: ''
  },
  {
    id: 'job-38',
    title: 'Laundry Shop Supervisor',
    title_hi: 'लॉन्ड्री सुपरवाइजर',
    category: 'Retail',
    salary: '₹13,000 / month',
    distance: '2.8 km',
    employerName: 'SpinDry',
    verified: true,
    rating: 4.5,
    description: 'Manage small team, quality checks and customer pickup.',
    description_hi: 'छोटी टीम का प्रबंधन, गुणवत्ता जाँच और ग्राहक पिकअप।',
    location: 'Mangalore, Karnataka',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-39',
    title: 'Packaging Operator',
    title_hi: 'पैकेजिंग ऑपरेटर',
    category: 'Manufacturing',
    salary: '₹10,200 / month',
    distance: '9.0 km',
    employerName: 'PackRight',
    verified: false,
    rating: 4.0,
    description: 'Package products and label them for shipping.',
    description_hi: 'उत्पादों को पैक करें और शिपिंग के लिए लेबल करें।',
    location: 'Kolhapur, Maharashtra',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-40',
    title: 'Canteen Helper',
    title_hi: 'कैंटीन सहायक',
    category: 'Food',
    salary: '₹8,500 / month',
    distance: '1.6 km',
    employerName: 'Campus Canteen',
    verified: false,
    rating: 4.1,
    description: 'Assist in food preparation and serving in a small canteen.',
    description_hi: 'छोटी कैंटीन में भोजन तैयार करने और परोसने में मदद।',
    location: 'Puducherry',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-41',
    title: 'Hotel Porter',
    title_hi: 'होटल पोर्टर',
    category: 'Hospitality',
    salary: '₹10,000 / month',
    distance: '5.5 km',
    employerName: 'BayView Hotel',
    verified: true,
    rating: 4.4,
    description: 'Handle luggage, assist guests with directions and basics.',
    description_hi: 'लगेज संभालें, अतिथियों को निर्देश और बुनियादी सहायता दें।',
    location: 'Goa',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-42',
    title: 'Parcel Delivery (Walk)',
    title_hi: 'पार्सल डिलीवरी (पैदल)',
    category: 'Delivery',
    salary: '₹9,000 / month',
    distance: '0.4 km',
    employerName: 'LocalPost',
    verified: false,
    rating: 3.9,
    description: 'Deliver small parcels within a local zone on foot or bicycle.',
    description_hi: 'स्थानीय क्षेत्र में पैदल या साइकिल पर छोटे पार्सल वितरित करना।',
    location: 'Shillong, Meghalaya',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-43',
    title: 'Tea Stall Owner Assistant',
    title_hi: 'चाय स्टॉल मालिक सहायक',
    category: 'Food',
    salary: '₹9,500 / month',
    distance: '0.2 km',
    employerName: 'OldTown Tea',
    verified: false,
    rating: 4.0,
    description: 'Help with stall management, cash and supplies.',
    description_hi: 'स्टॉल प्रबंधन, नकदी और आपूर्ति में मदद।',
    location: 'Darjeeling, WB',
    shift: 'Morning/Evening',
    contact: ''
  },
  {
    id: 'job-44',
    title: 'Laundry Pickup Driver',
    title_hi: 'लॉन्ड्री पिकअप ड्राइवर',
    category: 'Transport',
    salary: '₹13,000 / month',
    distance: '3.7 km',
    employerName: 'QuickClean',
    verified: true,
    rating: 4.3,
    description: 'Collect and deliver laundry orders within city.',
    description_hi: 'शहर के भीतर लॉन्ड्री ऑर्डर एकत्र और वितरित करें।',
    location: 'Amritsar, Punjab',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-45',
    title: 'Shopkeeper Assistant (Clothing)',
    title_hi: 'कपड़ों की दुकान सहायक',
    category: 'Retail',
    salary: '₹11,000 / month',
    distance: '2.1 km',
    employerName: 'StyleHub',
    verified: false,
    rating: 4.0,
    description: 'Assist customers, fold clothes and manage inventory.',
    description_hi: 'ग्राहकों की सहायता करें, कपड़े तह करें और इन्वेंटरी प्रबंधित करें।',
    location: 'Gandhinagar, Gujarat',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-46',
    title: 'Mason Helper',
    title_hi: 'मेसन सहायता',
    category: 'Construction',
    salary: '₹480 / day',
    distance: '13.0 km',
    employerName: 'StoneBuild',
    verified: false,
    rating: 4.1,
    description: 'Support mason with materials, mixing mortar and prep work.',
    description_hi: 'मेसन को सामग्री, मार्टार मिलाना और तैयारी काम में सहायता करें।',
    location: 'Bilaspur, Chhattisgarh',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-47',
    title: 'Tiler',
    title_hi: 'टाइल लगाने वाला',
    category: 'Construction',
    salary: '₹650 / day',
    distance: '14.5 km',
    employerName: 'TileMasters',
    verified: true,
    rating: 4.5,
    description: 'Tile cutting and installation for floors and walls.',
    description_hi: 'फर्श और दीवारों के लिए टाइल कटिंग और इंस्टॉलेशन।',
    location: 'Udaipur, Rajasthan',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-48',
    title: 'Roof Cleaner',
    title_hi: 'छत साफ़ करने वाला',
    category: 'Maintenance',
    salary: '₹500 / visit',
    distance: '6.8 km',
    employerName: 'CleanTop',
    verified: false,
    rating: 4.0,
    description: 'Clean terraces and remove debris from roofs.',
    description_hi: 'छतों से मलबा हटाना और टैरेस साफ करना।',
    location: 'Siliguri, WB',
    shift: 'Day',
    contact: ''
  },
  {
    id: 'job-49',
    title: 'Helper (Hotel Kitchen)',
    title_hi: 'होटल किचन सहायक',
    category: 'Hospitality',
    salary: '₹9,800 / month',
    distance: '3.2 km',
    employerName: 'OceanView',
    verified: false,
    rating: 4.1,
    description: 'Assist chefs, prep ingredients and clean utensils.',
    description_hi: 'शेफ की मदद करें, सामग्री तैयार करें और बर्तन साफ़ करें।',
    location: 'Port Blair, Andaman',
    shift: 'Morning/Evening',
    contact: ''
  },
  {
    id: 'job-50',
    title: 'Helper (Retail Stock)',
    title_hi: 'रिटेल स्टॉक सहायक',
    category: 'Retail',
    salary: '₹10,000 / month',
    distance: '2.0 km',
    employerName: 'UrbanStore',
    verified: true,
    rating: 4.2,
    description: 'Unload shipments, stock shelves and assist inventory checks.',
    description_hi: 'शिपमेंट अनलोड करें, सामान स्टॉक करें और इन्वेंटरी जांच में मदद करें।',
    location: 'Bhatinda, Punjab',
    shift: 'Day',
    contact: ''
  }
]

export default jobs
